In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.7.1" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia CSV DataFrames Random Statistics Distributions LinearAlgebra SparseArrays Printf JWAS"  # CSV DataFrames Random Statistics JWAS Distributions LinearAlgebra
JULIA_PACKAGES_IF_GPU=""
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.7.1 on the current Colab Runtime...
2022-08-01 04:12:08 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.7/julia-1.7.1-linux-x86_64.tar.gz [123374573/123374573] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...
Installing Julia package CSV...
Installing Julia package DataFrames...
Installing Julia package Random...
Installing Julia package Statistics...
Installing Julia package JWAS...
Installing IJulia kernel...
[ Info: Installing julia kernelspec in /root/.local/share/jupyter/kernels/julia-1.7

Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then
jump to the 'Checking the Installation' section.


In [1]:
versioninfo()

Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4


In [2]:
a=2.5
5a

12.5

In [3]:
a,b=1,2

(1, 2)

In [4]:
2-element Vector{Int64}:
 1
 2

LoadError: ignored

In [5]:
# easy swapping of values
a,b = b,a


(2, 1)

In [6]:
# Example
1 < a < 3

true

In [7]:
# empty vector of double precision floats
v = Array{Float64,1}()

Float64[]

In [8]:
push!(v,2.0)


1-element Vector{Float64}:
 2.0

In [9]:
push!(v,3.6)

2-element Vector{Float64}:
 2.0
 3.6

In [10]:
# vector of size 5, double precision floats
u =  Array{Float64,1}(undef, 5) #Float 64 is a way to save data in 64 bits/ float 32 meaning save in 32 bits

5-element Vector{Float64}:
 5.0e-324
 6.93935005038874e-310
 5.0e-324
 6.9393500503919e-310
 0.0

In [11]:
# matrix of size 3x5, double precision floats
U =  Array{Float64,2}(undef, 3,5)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [12]:
# vector of size 5, of 2.2
u =  fill(2.2,6)

6-element Vector{Float64}:
 2.2
 2.2
 2.2
 2.2
 2.2
 2.2

In [13]:
zeros(3,5)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [14]:
zero(U) #U means undefined matrix

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [15]:
ones(3,5)

3×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [16]:
using Random, Statistics, Distributions, LinearAlgebra, DataFrames, StatsPlots

LoadError: ignored

In [17]:
using Pkg #same as Library in R 

In [18]:
Pkg.add("StatsPlots") #same as install pacakage in R

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed x265_jll ───────────────────── v3.5.0+0
   Installed JpegTurbo_jll ──────────────── v2.1.2+0
   Installed libfdk_aac_jll ─────────────── v2.0.2+0
   Installed GR_jll ─────────────────────── v0.66.0+0
   Installed Libmount_jll ───────────────── v2.35.0+0
   Installed LERC_jll ───────────────────── v3.0.0+1
   Installed FFTW ───────────────────────── v1.5.0
   Installed OffsetArrays ───────────────── v1.12.7
   Installed Opus_jll ───────────────────── v1.3.2+0
   Installed LoggingExtras ──────────────── v0.4.9
   Installed RelocatableFolders ─────────── v0.3.0
   Installed Xorg_xkbcomp_jll ───────────── v1.4.2+4
   Installed EarCut_jll ─────────────────── v2.2.3+0
   Installed Measures ───────────────────── v0.3.1
   Installed Grisu ──────────────────────── v1.0.2
   Installed Xorg_xcb_util_wm_jll ───────── v0.4.1+1
   Installed Xorg_xcb_util_image_jll ────── v0.4.0+1
   Installed Pl

LoadError: ignored

In [19]:
rand(3,5) # uniform(0,1), default is between 0 to 1 

3×5 Matrix{Float64}:
 0.857611  0.993528  0.775305   0.417693  0.592505
 0.544184  0.977691  0.0450235  0.3603    0.421726
 0.609561  0.453337  0.694465   0.947961  0.0957545

In [20]:
mean(randn(1_000_000)) #calcualte the mean of 1 million number 

0.0003474691669313613

In [21]:
var(randn(1_000_000))

0.999358966520402

In [22]:
Random.seed!(100)

TaskLocalRNG()

In [23]:
M = rand(Binomial(2,0.5),10,20) #n=2 (2 independent Bernolli experiments), probability of success is 0.5 in each experiment, 10*20 matrix

10×20 Matrix{Int64}:
 2  1  0  2  0  1  1  0  0  0  0  1  2  2  0  0  2  1  1  0
 0  1  0  0  2  0  1  1  0  1  1  1  2  0  1  0  2  0  1  2
 2  0  1  0  0  0  2  1  2  1  2  0  0  1  0  0  1  1  1  2
 1  1  2  1  0  1  2  2  1  1  1  0  1  2  1  2  2  1  0  1
 2  0  1  2  2  2  1  0  1  2  1  1  1  1  2  2  0  0  0  1
 1  2  1  1  1  1  2  2  1  1  1  1  1  1  1  2  0  1  1  2
 1  1  0  1  0  1  2  1  2  1  0  1  1  2  1  1  1  1  1  0
 1  1  1  2  1  1  1  1  2  0  0  1  0  0  0  1  2  2  2  0
 1  1  1  1  2  0  1  1  2  1  1  1  0  0  1  1  1  1  0  1
 2  1  1  2  1  0  0  0  0  1  2  2  1  1  2  1  1  2  2  1

In [24]:
M[:,1] #extract all the row of the 1st columnn 

10-element Vector{Int64}:
 2
 0
 2
 1
 2
 1
 1
 1
 1
 2

In [25]:
M[1,:]'M[1,:]

26

In [26]:
M'M == M'*M

true

In [29]:
1I(3) #times 1

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

In [30]:
A = M'M + I #define A  adding I 

20×20 Matrix{Int64}:
 22  10  11  18  10  10  16   9  14  …  12  11  15  12  13  14  14  12  12
 10  12   7  11   8   6  12  10   9      9   9   9   8  10  11  10   9   9
 11   7  11  10   7   6  11   9  10      6   5   8   8  11   9   9   6   9
 18  11  10  21  11  11  13   8  12     13  11  13  12  14  14  14  12   8
 10   8   7  11  16   6   9   7   9     10   8   4  11  10   9   7   7  11
 10   6   6  11   6  10  10   6   8  …   6   7   9   7  10   7   6   5   5
 16  12  11  13   9  10  22  15  17      9  11  15  10  14  15  12  10  14
  9  10   9   8   7   6  15  14  12      6   7   9   7  11  11   9   7  11
 14   9  10  12   9   8  17  12  20      8   5  10   8  12  12  12   9  10
 12   7   8  10  10   7  12   8  10      8   8   9  11  11   8   7   6  11
 13   7   9   9   9   4  11   8   9  …   8   7   8  10   9   9   9   8  13
 12   9   6  13  10   6   9   6   8     12   9   8  10   9  10  10  10   8
 11   9   5  11   8   7  11   7   5      9  14  11   9   8  12   7   8   9
 15 

In [32]:
B = rand(3,3) + I

3×3 Matrix{Float64}:
 1.45742     0.905428  0.428537
 0.00450378  1.4083    0.831837
 0.26018     0.940167  1.68669

In [33]:
B*I

3×3 Matrix{Float64}:
 1.45742     0.905428  0.428537
 0.00450378  1.4083    0.831837
 0.26018     0.940167  1.68669

In [34]:
Diagonal(A) #give all the diagnol value in this matrix 

20×20 Diagonal{Int64, Vector{Int64}}:
 22   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅  12   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅  11   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  21   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅  16   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅  10   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  22   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  14   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  20      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅     12   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅  14   ⋅   ⋅   ⋅   ⋅

In [35]:
B = A[1:2,3:4] #extract row 1 and 2, column 3 to 4

2×2 Matrix{Int64}:
 11  18
  7  11